app:
  title: liatrio ootb GitLab Backstage
  baseUrl:
    $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#app.baseUrl

organization:
  name: liatrio ootb

backend:
  baseUrl:
    $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#backend.baseUrl
  listen:
    port:
      $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#backend.listen.port
  auth:
    $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#backend.auth
  # Disable upgrade-insecure-requests to prevent SSL errors
  csp:
    $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#backend.csp
  securityHeaders:
    $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#backend.securityHeaders
  # Use in-memory SQLite for local development
  database:
    client: better-sqlite3
    connection: ':memory:'
  # Configure CORS for both external and internal access
  cors:
    origin:
      $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#backend.cors.origin
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

auth:
  $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#auth

proxy:
  endpoints:
    '/gitlab/api':
      target: https://gitlab.com/api/v4

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'docker'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

gitlab:
  # immobiliare/backstage-plugin-gitlab plugin config
  defaultCodeOwnersPath: .gitlab/CODEOWNERS
  defaultReadmePath: .gitlab/README.md
  allowedKinds: ['Component', 'Resource']
  proxySecure: false
  useOAuth: true
  cache:
    enabled: true
    ttl: 300

integrations:
  gitlab:
    - host: gitlab.com
      token: ${BACKSTAGE_GITLAB_TOKEN}

scaffolder:
  actions:
    $all:
      useUserCredential: true

catalog:
  providers:
    # by default only Component, API, System are allowed from providers
    gitlab:
      liatrio:
        host: gitlab.com
        group: liatrioinc/client-solutions
        branch: main
        include_subgroups: true
        schedule:
          frequency: { minutes: 30 }
          timeout: { minutes: 10 }

  locations:
    $include: app-config.${BACKSTAGE_ENVIRONMENT}.yaml#catalog.locations
