app:
  baseUrl: http://localhost:7008
  
backend:
  # Backend should be accessible on the host port
  # We ONLY need a different port for local development when Backstage ran on the machine
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
  csp:
    upgrade-insecure-requests: false
  securityHeaders:
    strictTransportSecurity: ''

  cors:
    origin: http://localhost:7008

auth:
  # Add this to enable the guest sign-in page
  allowGuestAccess: true
  # Enable guest auth for local development
  providers:
    gitlab:
      development:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
    guest: {}
  # Enable legacy guest mode as a fallback
  legacyGuestToken: 'guest'
  environment: development
  session:
    secret: '${BACKEND_SECRET}'

catalog:
  # Use correct paths for catalog entities in the container
  locations:
    # Backstage entity schema
    - type: file
      target: ./../../company/entity-schema/catalog-info.yaml
      rules:
        - allow: [Component]

    - type: file
      target: ./../../company/sdp.yaml
      rules:
        - allow: [Domain, System, Group, User]

    - type: file
      target: ./../../company/gitlab-users.yaml
      rules:
        - allow: [User]
      schedule:
        frequency: { minutes: 120 }
        timeout: { minutes: 10 }

    - type: url
      target: https://gitlab.com/liatrioinc/client-solutions/backstage/backstage-add-java-pipeline-template/-/blob/main/template.yaml?ref_type=heads
      rules:
        - allow: [Template]

    # - type: url
    #   target: https://gitlab.com/<company>/ccis/tech-infrastructure-can/sdp/elevate-devx/backstage/backstage-template-list/-/blob/main/templates.yaml?ref_type=heads
    #   rules:
    #     - allow: [Template]

    # - type: url
    #   target: https://gitlab.com/<company>/ccis/tech-infrastructure-can/sdp/elevate-devx/backstage/backstage-template-list/-/blob/main/catalog-info.yaml?ref_type=heads
    #   rules:
    #     - allow: [Component]

    # - type: url
    #   target: https://gitlab.com/<company>/ccis/tech-infrastructure-can/sdp/workshops/liatrio-workshop/backstage/maven-jib-sample/-/blob/main/catalog-info.yaml?ref_type=heads
    #   rules:
    #     - allow: [Component]

    # how to reference a local file template in another cloned down repo
    # - type: file
    #   target: ./../../../java-maven-project-template/template.yaml
    #   rules:
    #     - allow: [Template]
