site_name: "GitLab Backstage Playbook"
docs_dir: docs
nav:
  - GitLab Backstage Implementation: backstage-implementation-playbook.md
  - Backstage Design Document: backstage-design-document.md
plugins:
  - techdocs-core