---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# example user entry for GitLab user with username `amber-beasley-liatrio`
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: amber-beasley-liatrio
spec:
  memberOf: [guests]

